version: '3.8'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}

services:
  ### php7.2  #########################################
  php-fpm-7.2:
    image: 'donglf681/php:7.2-fpm-alpine3.12-v2'
    network_mode: 'host'
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  ### php7.2-cli  #########################################
  swoft:
    image: 'donglf681/php:7.2-cli-alpine3.12'
    network_mode: 'host'
    volumes:
      - ${APP_CODE_PATH_HOST}/swoft:/var/www:rw
    ports:
      - '18306:18306'
    command: 'php bin/swoft http:start'

  ### NGINX Server #########################################
  nginx:
    image: 'donglf681/nginx:1.17-alpine'
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${APP_CODE_PATH_HOST}/dev.env/nginx/logs:/var/log/nginx:rw
      - ${APP_CODE_PATH_HOST}/dev.env/nginx/vhost:/etc/nginx/vhost
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php-fpm-7.2
    network_mode: 'host'

  ### Redis ################################################
  redis:
    image: 'donglf681/redis:5.0.9-alpine3.12'
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    # network_mode: 'host'
    networks:
      - backend

  ### phpcs ################################################
  phpcs:
    image: 'donglf681/phpcs:3.5.6'
    tty: true
    container_name: 'phpcs'
    volumes:
      - /tmp:/tmp
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_HOST}:rw

  ### phpcbf ################################################
  phpcbf:
    image: 'donglf681/phpcbf:3.5.6'
    tty: true
    container_name: 'phpcbf'
    volumes:
      - /tmp:/tmp
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_HOST}:rw

  ### MySQL ################################################
  mysql-5.7:
    image: 'donglf681/mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - mysql:/var/lib/mysql
      - ${APP_CODE_PATH_HOST}:/var/www:rw
    ports:
      - '${MYSQL_PORT}:3306'
    network_mode: 'host'
    # networks:
    #   - backend

  ### php7.2-cli  #########################################
  hyperf:
    image: 'donglf681/php:7.2-cli-alpine3.12-v2'
    # network_mode: 'host'
    networks:
      - backend
    volumes:
      - ${APP_CODE_PATH_HOST}/eadmin/api:/var/www:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - '9511:9501'
    command: 'php bin/hyperf.php start'

  ### jdk:1.8.0_202-alpine3.12#########################################
  anxinqian:
    image: 'donglf681/jdk:1.8.0-alpine3.12'
    network_mode: 'host'
    # networks:
    #   - backend
    volumes:
      - ${APP_CODE_PATH_HOST}/AnxinSign:/var/www:rw
    ports:
      - '1234:1234'
    command: 'java -jar AnxinSign.jar'

  ### jdk:1.8.0_202-alpine3.12 tomcat6.0 #########################################
  tomcat:
    # image: 'donglf681/jdk:1.8.0-alpine3.12'
    image: 'donglf681/tomcat:6.0-alpine3.12'
    network_mode: 'host'
    # networks:
    #   - backend
    volumes:
      - ./tomcat/sealConfig:/usr/local/apache-tomcat-6.0.32/bin/sealConfig:rw
      - ./tomcat/webapps/Seal.war:/usr/local/apache-tomcat-6.0.32/webapps/Seal.war:rw
      - ./tomcat/logs:/usr/local/apache-tomcat-6.0.32/logs:rw
      - ${APP_CODE_PATH_HOST}:/var/www:rw
    ports:
      - '8080:8080'
    command: 'catalina.sh run'
